config/routes.rb
Blog14::Application.routes.draw do
  resources :authors

  resources :sessions, only: [ :new, :create, :destroy ]
  match '/login', to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'get'

  match '/posts/recent', to: 'posts#recent', via: 'get'
  resources :posts
  begin
    prefix = if Blog14::YEARLY_BLOG then 'posts' else 'posts/:year' end
    get "#{prefix}/:month/:day/:id" => 'posts#show', as: :permalink
    get "#{prefix}/:month" => 'posts#monthly_index'
  end
  root 'posts#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_to_bootstrap(key)
      { 'notice' => 'info' }[key] || key.to_s
  end

  def link_to_post(title, post)
    created_at = post.created_at
    pairs = %w(year month day).map do |s|
      [ s.to_sym, created_at.send(s) ]
    end
    params = Hash[pairs]
    params[:id] = post.id

    params.delete(:year) if Blog14::YEARLY_BLOG

    link_to title, permalink_path(params)
  end

  def permalink(post)
    created_at = post.created_at
    pairs = %w(year month day).map do |s|
      [ s.to_sym, created_at.send(s) ]
    end
    params = Hash[pairs]
    params[:id] = post.id

    params.delete(:year) if Blog14::YEARLY_BLOG
    permalink_url(params)
  end
end

app/views/application/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse"
        data-target="#global-header">
        <i class="fa fa-bars"></i>
      </button>

      <%= link_to root_path, class: 'navbar-brand' do %>
        <span class="glyphicon glyphicon-home"></span> Home
      <% end %>
    </div>

    <div class="navbar-collapse collapse" id="global-header">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-rss"></i> Atom <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to('Mixed', posts_recent_url(:format => :atom)) %></li>
            <li class="divider"></li>
            <% Post.used_languages.each do |lang| %>
            <li><%= link_to(Post.all_languages[lang], posts_recent_url(:format => :atom, :language => lang)) %></li>
            <% end %>
          </ul>
        </li>

        <% if current_author %>
        <li>
          <%= link_to new_post_path do %>
            <span class="glyphicon glyphicon-pencil"></span> New Post
          <% end %>
        </li>
        <li>
          <%= link_to logout_path do %>
            <span class="glyphicon glyphicon-log-in"></span> Logout
          <% end %>
        </li>
        <% else %>
        <li>
          <%= link_to login_path do %>
            <span class="glyphicon glyphicon-log-out"></span> Login
          <% end %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>